CREATE TABLE webcam_logs(
id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
webcam_id VARCHAR(64) NOT NULL,
ts DATETIME NOT NULL,
marks INT NOT NULL DEFAULT 0,
memo VARCHAR(255) NOT NULL DEFAULT '',
modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE KEY (webcam_id,ts)
);

CREATE TABLE webcam_logs_dailies(
webcam_id VARCHAR(64) NOT NULL,
ts DATE NOT NULL,
n INT NOT NULL DEFAULT 0,
sum_marks INT NOT NULL DEFAULT 0,
max_marks INT NOT NULL DEFAULT 0,
max_marks_id INT NOT NULL,
modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY (webcam_id,ts)
);

CREATE TABLE bme280_logs(
id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
raspi_id INTEGER NOT NULL DEFAULT 0,
ts DATETIME NOT NULL,
temperature FLOAT,
pressure FLOAT,
humidity FLOAT,
modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE KEY (raspi_id,ts)
);

CREATE TABLE bme280_logs_dailies(
raspi_id INTEGER NOT NULL DEFAULT 0,
ts DATE NOT NULL,
n INT NOT NULL DEFAULT 0,
temperature_avg FLOAT,
temperature_min FLOAT,
temperature_max FLOAT,
pressure_avg FLOAT,
pressure_min FLOAT,
pressure_max FLOAT,
humidity_avg FLOAT,
humidity_min FLOAT,
humidity_max FLOAT,
modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
PRIMARY KEY(raspi_id,ts)
);
