CREATE TABLE webcam_logs(
id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
webcam_id VARCHAR(64) NOT NULL,
ts DATETIME NOT NULL,
marks INT NOT NULL DEFAULT 0,
memo VARCHAR(255) NOT NULL DEFAULT '',
modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE KEY (webcam_id,ts)
);

CREATE TABLE webcam_logs_dailies(
id INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
webcam_id VARCHAR(64) NOT NULL,
ts DATE NOT NULL,
n INT NOT NULL DEFAULT 0,
sum_marks INT NOT NULL DEFAULT 0,
max_marks INT NOT NULL DEFAULT 0,
max_marks_id INT,
modified_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
UNIQUE KEY (webcam_id,ts)
);
